### ISSUE TITLE
[REQ] pornstarbyface.com

### ISSUE THREAD

**Issue by wilde018** [bebasid/bebasid#523]
I believe this is a new site, right?

**Comment by nxzlem** [comment]
Dear, @wilde018.
Yes, it's a new site and it's blocked by TrustPositif.
Because the site pornstarbyface.com (https://github.com/bebasid/bebasid/commit/249c177cc62819083a24dce4daaae8bd0a0bb450) has not yet been added to the host's bebasid database, I am adding it now. 

Please update your computer hosts in addition to the device as well, so that the host stays updated to the latest version. Your issue will be closed in 3–7 days if there is no response. If there is still a problem after the issue has been closed. Please reopen the issue and provide the reason why and evidence that it is not working.

That's all, thank you.
From @nxzlem.
